name: Clear Cache
on: push

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear GitHub Actions cache
        run: |
          rm -rf ${{ github.workspace }}/_actions
          rm -rf ${{ github.workspace }}/_work